# Generated by Django 3.0.8 on 2020-07-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
